server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: [__meta_docker_container_label_logging]
        regex: promtail
        action: keep
      - source_labels: [__meta_docker_container_name]
        target_label: container
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: service
      - source_labels: [__meta_docker_container_log_stream]
        target_label: stream
      - source_labels: [__meta_docker_container_log_path]
        target_label: __path__
    pipeline_stages:
      - json:
          expressions:
            ts: asctime
            lvl: levelname
            logger: name
            msg: message
            request_id: request_id
            user_id: user_id
            handler: handler
            duration_ms: duration_ms
      - labels:
          service:
          container:
          handler:
          user_id:

