rgti = "<TA>RGTI has shown a bullish trend in the last 24 hours, with a notable increase in trading volume. The stock price has broken through a key resistance level, indicating potential for further gains. Technical indicators suggest a strong momentum, with the RSI moving into overbought territory. Investors should watch for any pullbacks as a buying opportunity.</TA> <CN>No significant data.</CN> <WN>No significant data.</WN> <IC>No significant data.</IC> <COMP>No significant data.</COMP> <LEGAL>No significant data.</LEGAL> <FIN>No significant data.</FIN>"
qbt = "<TA>QBTS has shown a bullish trend in the last 24 hours, with a notable increase in trading volume. The stock price has bounced back from recent lows, indicating potential upward momentum. Key resistance levels are being tested, and traders are watching for breakouts. Overall, technical indicators suggest a positive outlook. <CN>No significant data.</CN><WN>No significant data.</WN><IC>No significant data.</IC><COMP>No significant data.</COMP><LEGAL>No significant data.</LEGAL><FIN>No significant data."
ionq = "<TA>IONQ's stock has shown a bullish trend in the last 24 hours, with a notable increase in trading volume. The price movement suggests strong buying interest, potentially indicating a breakout above resistance levels. Technical indicators are also reflecting positive momentum, which could attract further investor interest. Overall, the technical outlook appears favorable. </TA><CN>IONQ announced a partnership with a leading tech firm to enhance its quantum computing capabilities, which has been positively received by the market. This collaboration is expected to accelerate product development and expand market reach. Investors are optimistic about the potential revenue growth stemming from this alliance. The news has contributed to a positive sentiment around the stock. </CN><WN>No significant data.</WN><IC>No significant data.</IC><COMP>No significant data.</COMP><LEGAL>No significant data.</LEGAL><FIN>IONQ's recent financial performance has shown promise, with analysts projecting an increase in revenue due to new contracts. The market is reacting favorably to these projections, which may lead to upward revisions in earnings estimates. Investors are closely monitoring the company's financial health as it continues to expand. </FIN>"
hwm = "<TA>HWM has shown a bullish trend in the last 24 hours, with a notable increase in trading volume. The stock price has broken through a key resistance level, indicating potential for further gains. Momentum indicators suggest continued upward movement, but traders should watch for any signs of overextension. Overall, the technical outlook remains positive.</TA> <CN>No significant data.</CN> <WN>No significant data.</WN> <IC>No significant data.</IC> <COMP>No significant data.</COMP> <LEGAL>No significant data.</LEGAL> <FIN>No significant data.</FIN>"
tsla = "<TA>TSLA's stock has shown a bullish trend in the last 24 hours, with a notable increase of 3.5% in its share price. The trading volume was above average, indicating strong investor interest. Key resistance levels are being tested, suggesting potential for further upward movement. Analysts are watching for confirmation of this trend in the coming days.</TA> <CN>No significant data.</CN> <WN>No significant data.</WN> <IC>No significant data.</IC> <COMP>No significant data.</COMP> <LEGAL>No significant data.</LEGAL> <FIN>No significant data.</FIN>"




